# Generated by Django 4.1 on 2022-08-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_rename_typefood_food_type_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='type_food',
            new_name='typefood',
        ),
    ]
